def test_broken_addition():
    assert 2 + 2 == 5  # This test will fail
